settings:
  docker:
    parent_image: your-registry.azurecr.io/zenml-base:latest
    skip_build: True
  orchestrator.azureml:
    synchronous: false

parameters:
  artifact_names:
    - raw_documents
    - cleaned_documents
    - instruct_datasets
    - preference_datasets
