settings:
  docker:
    parent_image: your-registry.azurecr.io/zenml-base:latest
    skip_build: True
  orchestrator.azureml:
    synchronous: false

parameters:
  test_split_size: 0.1
  dataset_type: "instruction"
  push_to_huggingface: true
  dataset_id: pauliusztin/llmtwin
  mock: false
